/// @file

//#include "precompiled.hpp"

efx_api_t gEfxAPI =
    {
        CL_AllocParticle,
        (void *)CL_BlobExplosion,
        (void *)CL_Blood,
        (void *)CL_BloodSprite,
        (void *)CL_BloodStream,
        (void *)CL_BreakModel,
        (void *)CL_Bubbles,
        (void *)CL_BubbleTrail,
        (void *)CL_BulletImpactParticles,
        CL_EntityParticles,
        CL_Explosion,
        CL_FizzEffect,
        CL_FireField,
        (void *)CL_FlickerParticles,
        (void *)CL_FunnelSprite,
        (void *)CL_Implosion,
        (void *)CL_Large_Funnel,
        (void *)CL_LavaSplash,
        (void *)CL_MultiGunshot,
        (void *)CL_MuzzleFlash,
        (void *)CL_ParticleBox,
        (void *)CL_ParticleBurst,
        (void *)CL_ParticleExplosion,
        (void *)CL_ParticleExplosion2,
        (void *)CL_ParticleLine,
        CL_PlayerSprites,
        (void *)CL_Projectile,
        (void *)CL_RicochetSound,
        (void *)CL_RicochetSprite,
        (void *)CL_RocketFlare,
        CL_RocketTrail,
        (void *)CL_RunParticleEffect,
        (void *)CL_ShowLine,
        (void *)CL_SparkEffect,
        (void *)CL_SparkShower,
        (void *)CL_SparkStreaks,
        (void *)CL_Spray,
        CL_Sprite_Explode,
        CL_Sprite_Smoke,
        (void *)CL_Sprite_Spray,
        (void *)CL_Sprite_Trail,
        CL_Sprite_WallPuff,
        (void *)CL_StreakSplash,
        (void *)CL_TracerEffect,
        CL_UserTracerParticle,
        CL_TracerParticles,
        (void *)CL_TeleportSplash,
        (void *)CL_TempSphereModel,
        (void *)CL_TempModel,
        (void *)CL_DefaultSprite,
        (void *)CL_TempSprite,
        CL_DecalIndex,
        (void *)CL_DecalIndexFromName,
        CL_DecalShoot,
        CL_AttachTentToPlayer,
        CL_KillAttachedTents,
        (void *)CL_BeamCirclePoints,
        (void *)CL_BeamEntPoint,
        CL_BeamEnts,
        CL_BeamFollow,
        CL_BeamKill,
        (void *)CL_BeamLightning,
        (void *)CL_BeamPoints,
        (void *)CL_BeamRing,
        CL_AllocDlight,
        CL_AllocElight,
        (void *)CL_TempEntAlloc,
        (void *)CL_TempEntAllocNoModel,
        (void *)CL_TempEntAllocHigh,
        (void *)CL_TempEntAllocCustom,
        CL_GetPackedColor,
        CL_LookupColor,
        CL_DecalRemoveAll,
        CL_FireCustomDecal};